#include "cpu.h"


const CPU::InstructionTableEntry CPU::UNDEFINED_INSTRUCTION_TABLE_ENTRY = {INSTRUCTION_UNDEFINED, ADDRESSMODE_UNDEFINED};

const CPU::InstructionTableEntry CPU::instructionTable[INSTRUCTION_TABLE_SIZE] =
{
	/*00*/ {INSTRUCTION_BRK, ADDRESSMODE_IMPLIED},     {INSTRUCTION_ORA, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*04*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ORA, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_ASL, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*08*/ {INSTRUCTION_PHP, ADDRESSMODE_IMPLIED},     {INSTRUCTION_ORA, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_ASL, ADDRESSMODE_ACCUMULATOR}, UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*0C*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ORA, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_ASL, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*10*/ {INSTRUCTION_BPL, ADDRESSMODE_RELATIVE},    {INSTRUCTION_ORA, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*14*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ORA, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_ASL, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*18*/ {INSTRUCTION_CLC, ADDRESSMODE_IMPLIED},     {INSTRUCTION_ORA, ADDRESSMODE_ABSOLUTE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*1C*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ORA, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_ASL, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*20*/ {INSTRUCTION_JSR, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_AND, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*24*/ {INSTRUCTION_BIT, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_AND, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_ROL, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*28*/ {INSTRUCTION_PLP, ADDRESSMODE_IMPLIED},     {INSTRUCTION_AND, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_ROL, ADDRESSMODE_ACCUMULATOR}, UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*2C*/ {INSTRUCTION_BIT, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_AND, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_ROL, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*30*/ {INSTRUCTION_BMI, ADDRESSMODE_RELATIVE},    {INSTRUCTION_AND, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*34*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_AND, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_ROL, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*38*/ {INSTRUCTION_SEC, ADDRESSMODE_IMPLIED},     {INSTRUCTION_AND, ADDRESSMODE_ABSOLUTE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*3C*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_AND, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_ROL, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*40*/ {INSTRUCTION_RTI, ADDRESSMODE_IMPLIED},     {INSTRUCTION_EOR, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*44*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_EOR, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_LSR, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*48*/ {INSTRUCTION_PHA, ADDRESSMODE_IMPLIED},     {INSTRUCTION_EOR, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_LSR, ADDRESSMODE_ACCUMULATOR}, UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*4C*/ {INSTRUCTION_JMP, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_EOR, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_LSR, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*50*/ {INSTRUCTION_BVC, ADDRESSMODE_RELATIVE},    {INSTRUCTION_EOR, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*54*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_EOR, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_LSR, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*58*/ {INSTRUCTION_CLI, ADDRESSMODE_IMPLIED},     {INSTRUCTION_EOR, ADDRESSMODE_ABSOLUTE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*5C*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_EOR, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_LSR, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*60*/ {INSTRUCTION_RTS, ADDRESSMODE_IMPLIED},     {INSTRUCTION_ADC, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*64*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ADC, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_ROR, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*68*/ {INSTRUCTION_PLA, ADDRESSMODE_IMPLIED},     {INSTRUCTION_ADC, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_ROR, ADDRESSMODE_ACCUMULATOR}, UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*6C*/ {INSTRUCTION_JMP, ADDRESSMODE_INDIRECT},    {INSTRUCTION_ADC, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_ROR, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*70*/ {INSTRUCTION_BVS, ADDRESSMODE_RELATIVE},    {INSTRUCTION_ADC, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*74*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ADC, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_ROR, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*78*/ {INSTRUCTION_SEI, ADDRESSMODE_IMPLIED},     {INSTRUCTION_ADC, ADDRESSMODE_ABSOLUTE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*7C*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_ADC, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_ROR, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*80*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_STA, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*84*/ {INSTRUCTION_STY, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_STA, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_STX, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*88*/ {INSTRUCTION_DEY, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_TXA, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*8C*/ {INSTRUCTION_STY, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_STA, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_STX, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*90*/ {INSTRUCTION_BCC, ADDRESSMODE_RELATIVE},    {INSTRUCTION_STA, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*94*/ {INSTRUCTION_STY, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_STA, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_STX, ADDRESSMODE_ZEROPAGE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*98*/ {INSTRUCTION_TYA, ADDRESSMODE_IMPLIED},     {INSTRUCTION_STA, ADDRESSMODE_ABSOLUTE_Y},  {INSTRUCTION_TXS, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*9C*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_STA, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*A0*/ {INSTRUCTION_LDY, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_LDA, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*A4*/ {INSTRUCTION_LDY, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_LDA, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*A8*/ {INSTRUCTION_TAY, ADDRESSMODE_IMPLIED},     {INSTRUCTION_LDA, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_TAX, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*AC*/ {INSTRUCTION_LDY, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_LDA, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*B0*/ {INSTRUCTION_BCS, ADDRESSMODE_RELATIVE},    {INSTRUCTION_LDA, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*B4*/ {INSTRUCTION_LDY, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_LDA, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*B8*/ {INSTRUCTION_CLV, ADDRESSMODE_IMPLIED},     {INSTRUCTION_LDA, ADDRESSMODE_ABSOLUTE_Y},  {INSTRUCTION_TSX, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*BC*/ {INSTRUCTION_LDY, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_LDA, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*C0*/ {INSTRUCTION_CPY, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_CMP, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*C4*/ {INSTRUCTION_CPY, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_CMP, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_DEC, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*C8*/ {INSTRUCTION_INY, ADDRESSMODE_IMPLIED},     {INSTRUCTION_CMP, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_DEX, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*CC*/ {INSTRUCTION_CPY, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_CMP, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_DEC, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*D0*/ {INSTRUCTION_BNE, ADDRESSMODE_RELATIVE},    {INSTRUCTION_CMP, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*D4*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_CMP, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_DEC, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*D8*/ {INSTRUCTION_CLD, ADDRESSMODE_IMPLIED},     {INSTRUCTION_CMP, ADDRESSMODE_ABSOLUTE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*DC*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_CMP, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_DEC, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*E0*/ {INSTRUCTION_CPX, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_SBC, ADDRESSMODE_X_INDIRECT},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*E4*/ {INSTRUCTION_CPX, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_SBC, ADDRESSMODE_ZEROPAGE},    {INSTRUCTION_INC, ADDRESSMODE_ZEROPAGE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*E8*/ {INSTRUCTION_INX, ADDRESSMODE_IMPLIED},     {INSTRUCTION_SBC, ADDRESSMODE_IMMEDIATE},   {INSTRUCTION_NOP, ADDRESSMODE_IMPLIED},     UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*EC*/ {INSTRUCTION_CPX, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_SBC, ADDRESSMODE_ABSOLUTE},    {INSTRUCTION_INC, ADDRESSMODE_ABSOLUTE},    UNDEFINED_INSTRUCTION_TABLE_ENTRY,   

	/*F0*/ {INSTRUCTION_BEQ, ADDRESSMODE_RELATIVE},    {INSTRUCTION_SBC, ADDRESSMODE_INDIRECT_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*F4*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_SBC, ADDRESSMODE_ZEROPAGE_X},  {INSTRUCTION_INC, ADDRESSMODE_ZEROPAGE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*F8*/ {INSTRUCTION_SED, ADDRESSMODE_IMPLIED},     {INSTRUCTION_SBC, ADDRESSMODE_ABSOLUTE_Y},  UNDEFINED_INSTRUCTION_TABLE_ENTRY,          UNDEFINED_INSTRUCTION_TABLE_ENTRY,   
	/*FC*/ UNDEFINED_INSTRUCTION_TABLE_ENTRY,          {INSTRUCTION_SBC, ADDRESSMODE_ABSOLUTE_X},  {INSTRUCTION_INC, ADDRESSMODE_ABSOLUTE_X},  UNDEFINED_INSTRUCTION_TABLE_ENTRY
};


const CPU::PFNInstruction CPU::INSTRUCTIONS[NUM_INSTRUCTION] =
{
	&CPU::ADC, &CPU::AND, &CPU::ASL, &CPU::BCC, &CPU::BCS, &CPU::BEQ, &CPU::BIT, &CPU::BMI,
	&CPU::BNE, &CPU::BPL, &CPU::BRK, &CPU::BVC, &CPU::BVS, &CPU::CLC, &CPU::CLD, &CPU::CLI,
	&CPU::CLV, &CPU::CMP, &CPU::CPX, &CPU::CPY, &CPU::DEC, &CPU::DEX, &CPU::DEY, &CPU::EOR,
	&CPU::INC, &CPU::INX, &CPU::INY, &CPU::JMP, &CPU::JSR, &CPU::LDA, &CPU::LDX, &CPU::LDY,
	&CPU::LSR, &CPU::NOP, &CPU::ORA, &CPU::PHA, &CPU::PHP, &CPU::PLA, &CPU::PLP, &CPU::ROL,
	&CPU::ROR, &CPU::RTI, &CPU::RTS, &CPU::SBC, &CPU::SEC, &CPU::SED, &CPU::SEI, &CPU::STA,
	&CPU::STX, &CPU::STY, &CPU::TAX, &CPU::TAY, &CPU::TSX, &CPU::TXA, &CPU::TXS, &CPU::TYA
};